### PR TITLE
Homework String Manipulator

### PR DESCRIPTION
**Pull request by Sqaiser**
Professor please grade my work.

### CODE REVIEW

**Comment by khatchad** [comment]
Did I give you a grade for this in Blackboard?

**Comment by khatchad** [comment]
Closing this for now. We will reopen it if you did not receive a grade. Remember, I need your github user name submitted in Blackboard so that I can match up your code to your grade.

**Comment by Sqaiser** [comment]
Hello Professor,

Sorry for the late reply but my github username is Sqaiser.

Thank you

**Comment by khatchad** [comment]
Cool. Can you submit that on Blackboard so I can give you a grade?

**Pull request closed without merging**
